name: Sudoku CI
on:
  push:
    paths:
      - 'sudoku/**/*.py'
      - 'tests/**/*.py'
  pull_request:
    paths:
      - 'sudoku/**/*.py'
      - 'tests/**/*.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run test
        env:
            PYTHONPATH: .
        run: pytest tests/